add compiler flag
If newer compilers gives you errors like this

```
Uart.h:49:64: error: ISO C++17 does not allow dynamic exception specifications
   49 |                 UART(std::string tty, bool hwflowctrl = false) throw (UARTException);
      |                                                                ^~~~~
```

you need to add the `CXXFLAGS` option to `Makefile`.